/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cyberesicg.oscal_cprt.gui;

/**
 *
 * @author jimlh
 */
public class FwMapListPnl extends javax.swing.JPanel {

    /**
     * Creates new form mappingsListPanel
     *
     * @param srcFwName
     */
    public FwMapListPnl(String srcFwName) {
        initComponents();
        srcFwNameLbl.setText(srcFwName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        srcFwNameLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfMapsPnl = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanel6.setMinimumSize(new java.awt.Dimension(200, 25));
        jPanel6.setName(""); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(12, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(12, 0));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(12, 25));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel4);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 16));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 16));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        srcFwNameLbl.setText("Source Framework");
        srcFwNameLbl.setMaximumSize(new java.awt.Dimension(32767, 16));
        srcFwNameLbl.setMinimumSize(new java.awt.Dimension(200, 16));
        jPanel3.add(srcFwNameLbl);

        jPanel6.add(jPanel3);

        jPanel5.setMaximumSize(new java.awt.Dimension(12, 32767));
        jPanel5.setMinimumSize(new java.awt.Dimension(12, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(12, 25));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5);

        add(jPanel6);

        listOfMapsPnl.setMaximumSize(new java.awt.Dimension(32767, 0));
        listOfMapsPnl.setOpaque(false);
        listOfMapsPnl.setLayout(new javax.swing.BoxLayout(listOfMapsPnl, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(listOfMapsPnl);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listOfMapsPnl;
    private javax.swing.JLabel srcFwNameLbl;
    // End of variables declaration//GEN-END:variables
}
