/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cyberesicg.oscal_cprt.gui;

import com.cyberesicg.oscal_cprt.logic.CatalogDoc;
import com.cyberesicg.oscal_cprt.logic.CprtAccess;
import com.cyberesicg.oscal_cprt.logic.FwNameResolver;
import com.cyberesicg.oscal_cprt.logic.MappingDoc;
import com.cyberesicg.oscal_cprt.logic.AppUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jimlh
 */
public class MainGuiFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainGuiFrame
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public MainGuiFrame() throws URISyntaxException, IOException {
        initComponents();
        Preferences prefs = Preferences.userNodeForPackage(com.cyberesicg.oscal_cprt.logic.AppUtils.class);
        AppUtils.gOutFolder = prefs.get("gOutFolder", File.separator + ".");
        outFolderLbl.setText(AppUtils.gOutFolder);
        outFolderLbl.setToolTipText(AppUtils.gOutFolder);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int)(screenSize.getWidth() * 0.3);
        int height = (int)(screenSize.getHeight() * 0.5);
        setSize(width, height);
        setLocationRelativeTo(null);
        populateSelectionControls();
//        refreshListBtnActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        srcFrameworkSelect = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        makeSrcCatFileBtn = new javax.swing.JButton();
        makeTgtCatFileBtn = new javax.swing.JButton();
        updateCprtCacheBtn = new javax.swing.JButton();
        makeMapFileBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tgtFwsList = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        refreshListBtn = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        clrSelBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        prefsBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        outFolderLbl = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OSCAL Mapping");
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(33070, 70));
        jPanel2.setMinimumSize(new java.awt.Dimension(303, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(1606, 70));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel19.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel19.setMinimumSize(new java.awt.Dimension(15, 0));
        jPanel19.setPreferredSize(new java.awt.Dimension(15, 70));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel19);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cyber Engineering Services Consulting Group Inc.");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("OSCAL-CPRT Reference Mapping Tool");
        jPanel1.add(jLabel2);

        jPanel2.add(jPanel1);
        jPanel2.add(filler1);

        getContentPane().add(jPanel2);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jPanel10.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel10.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel20.setMaximumSize(new java.awt.Dimension(65685, 100));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setMinimumSize(new java.awt.Dimension(240, 51));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 47));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel15.setMaximumSize(new java.awt.Dimension(32906, 25));
        jPanel15.setMinimumSize(new java.awt.Dimension(139, 25));
        jPanel15.setPreferredSize(new java.awt.Dimension(235, 25));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Choose source (focal) CPRT framework");
        jLabel3.setMaximumSize(new java.awt.Dimension(240, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(240, 16));
        jPanel15.add(jLabel3);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16);

        jPanel4.add(jPanel15);

        srcFrameworkSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP 800-53 Rev 5", "CSF_1_1_0", "SP_800_221A_0_1_0", "SP_800_218_1_1_0", "NISTIR_8259B_1_0_0", "NISTIR_8259A_1_0_0", "SP_800_171_2_0_0", "SP_800_171_1_0_0", "PF_1_0_0", "SP_800_53_4_0_0", "CSF_2_0_0" }));
        srcFrameworkSelect.setToolTipText("");
        srcFrameworkSelect.setMaximumSize(new java.awt.Dimension(32767, 30));
        srcFrameworkSelect.setPreferredSize(new java.awt.Dimension(150, 22));
        srcFrameworkSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcFrameworkSelectActionPerformed(evt);
            }
        });
        jPanel4.add(srcFrameworkSelect);

        jPanel20.add(jPanel4);

        jPanel21.setMaximumSize(new java.awt.Dimension(12, 32767));
        jPanel21.setMinimumSize(new java.awt.Dimension(12, 0));
        jPanel21.setPreferredSize(new java.awt.Dimension(12, 155));
        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.Y_AXIS));
        jPanel20.add(jPanel21);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        makeSrcCatFileBtn.setText("Create catalog for source framework");
        makeSrcCatFileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        makeSrcCatFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeSrcCatFileBtnActionPerformed(evt);
            }
        });
        jPanel12.add(makeSrcCatFileBtn);

        makeTgtCatFileBtn.setText("Create catalog for target framework");
        makeTgtCatFileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        makeTgtCatFileBtn.setName(""); // NOI18N
        makeTgtCatFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTgtCatFileBtnActionPerformed(evt);
            }
        });
        jPanel12.add(makeTgtCatFileBtn);

        updateCprtCacheBtn.setText("Update local CPRT cache");
        updateCprtCacheBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        updateCprtCacheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCprtCacheBtnActionPerformed(evt);
            }
        });
        jPanel12.add(updateCprtCacheBtn);

        makeMapFileBtn.setText("Create mapping file");
        makeMapFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeMapFileBtnActionPerformed(evt);
            }
        });
        jPanel12.add(makeMapFileBtn);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13);

        jPanel20.add(jPanel12);

        jPanel3.add(jPanel20);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel17.setMaximumSize(new java.awt.Dimension(33007, 25));
        jPanel17.setMinimumSize(new java.awt.Dimension(340, 25));
        jPanel17.setPreferredSize(new java.awt.Dimension(371, 25));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Select target (reference) CPRT framework");
        jPanel17.add(jLabel4);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18);

        jPanel5.add(jPanel17);

        tgtFwsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SP 800-221A", "SSDF", "NISTIR 8259B", "NISTIR 8259A", "SP 800-171 Rev 2", "Privacy Framework", "Cybersecurity Framework v1.1", "SP 800-171 Rev 1", "SP 800-53 Rev 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(tgtFwsList);

        jPanel5.add(jScrollPane1);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        refreshListBtn.setText("Refresh List");
        refreshListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshListBtnActionPerformed(evt);
            }
        });
        jPanel7.add(refreshListBtn);
        jPanel7.add(filler3);

        clrSelBtn.setText("Clear Select");
        clrSelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrSelBtnActionPerformed(evt);
            }
        });
        jPanel7.add(clrSelBtn);

        jPanel5.add(jPanel7);

        jPanel3.add(jPanel5);

        jPanel9.add(jPanel3);

        jPanel11.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel11.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11);

        getContentPane().add(jPanel9);

        jPanel6.setMaximumSize(new java.awt.Dimension(32955, 55));
        jPanel6.setMinimumSize(new java.awt.Dimension(288, 55));
        jPanel6.setPreferredSize(new java.awt.Dimension(618, 55));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        prefsBtn.setText("Prefs");
        prefsBtn.setMargin(new java.awt.Insets(2, 2, 2, 2));
        prefsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefsBtnActionPerformed(evt);
            }
        });
        jPanel8.add(prefsBtn);

        jPanel6.add(jPanel8);

        jLabel5.setText("Out Folder:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 3));
        jPanel6.add(jLabel5);

        outFolderLbl.setText(".\\");
            outFolderLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1));
            outFolderLbl.setMaximumSize(new java.awt.Dimension(500, 18));
            outFolderLbl.setMinimumSize(new java.awt.Dimension(30, 18));
            outFolderLbl.setName(""); // NOI18N
            outFolderLbl.setPreferredSize(new java.awt.Dimension(450, 18));
            jPanel6.add(outFolderLbl);

            jPanel22.setMaximumSize(new java.awt.Dimension(32767, 25));
            jPanel22.setMinimumSize(new java.awt.Dimension(10, 25));

            javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
            jPanel22.setLayout(jPanel22Layout);
            jPanel22Layout.setHorizontalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 10, Short.MAX_VALUE)
            );
            jPanel22Layout.setVerticalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 25, Short.MAX_VALUE)
            );

            jPanel6.add(jPanel22);

            jPanel14.setMaximumSize(new java.awt.Dimension(20, 32767));
            jPanel14.setMinimumSize(new java.awt.Dimension(20, 0));
            jPanel14.setPreferredSize(new java.awt.Dimension(20, 55));

            javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
            jPanel14.setLayout(jPanel14Layout);
            jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 20, Short.MAX_VALUE)
            );
            jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 55, Short.MAX_VALUE)
            );

            jPanel6.add(jPanel14);

            getContentPane().add(jPanel6);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void populateSelectionControls(){
        srcFrameworkSelect.removeAllItems();
        for(String str: FwNameResolver.cprtFrameworks){
            str = FwNameResolver.resolveDisplayName(str);
            srcFrameworkSelect.addItem(str);
        }
        srcFrameworkSelect.setSelectedIndex(0);
        String srcStr = srcFrameworkSelect.getItemAt(0);
        
        tgtFwsList.removeAll();
        DefaultListModel fwList = new DefaultListModel();
        for(String str: FwNameResolver.cprtFrameworks){
            str = FwNameResolver.resolveDisplayName(str);
            if(str.equals(srcStr)) continue;
            fwList.addElement(str);
        }
        tgtFwsList.setModel(fwList);
    }
    
    private void clrSelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrSelBtnActionPerformed
        tgtFwsList.clearSelection();
    }//GEN-LAST:event_clrSelBtnActionPerformed

    private void refreshListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshListBtnActionPerformed
        //Build the list of frameworks that include references to the selected source framework
        CprtAccess ca = new CprtAccess();
        ArrayList<String> fws = new ArrayList<>();
        try {
            fws = ca.getFwList();
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MainGuiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel<String> m = new DefaultListModel<>();
        for(String str: fws){
            String srcFw = FwNameResolver.resolve((String)srcFrameworkSelect.getSelectedItem());
            String tgtFw = FwNameResolver.resolve(str);
            System.out.println("this is the string: "+str);
            if(tgtFw.equals(srcFw)) continue;
            str = FwNameResolver.resolveDisplayName(str);

            m.addElement(str);
        }
        tgtFwsList.setModel(m);
    }//GEN-LAST:event_refreshListBtnActionPerformed

    private void makeSrcCatFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeSrcCatFileBtnActionPerformed
        String srcFwName = String.valueOf(srcFrameworkSelect.getSelectedItem());
        srcFwName = FwNameResolver.resolve(srcFwName);

        CatalogDoc cd = new CatalogDoc(srcFwName);
        try {
            cd.makeCatalogDocument();
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(MainGuiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cd.writeCatalog();

//        FwMapListPnl mp = new FwMapListPnl(srcFwName);
//        MappingDoc md = new MappingDoc(srcFwName, sels);
//        md.populate();
//        md.writeMappingsFile();
    }//GEN-LAST:event_makeSrcCatFileBtnActionPerformed

    private void srcFrameworkSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcFrameworkSelectActionPerformed
        refreshListBtnActionPerformed(evt);
    }//GEN-LAST:event_srcFrameworkSelectActionPerformed

    private void prefsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefsBtnActionPerformed
        PrefsDialog.makeNewPrefsDlg(this);
    }//GEN-LAST:event_prefsBtnActionPerformed

    private void makeTgtCatFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTgtCatFileBtnActionPerformed
        String tgtFwName = tgtFwsList.getSelectedValue();
        tgtFwName = FwNameResolver.resolve(tgtFwName);
        CatalogDoc cd = new CatalogDoc(tgtFwName);
        try {
            cd.makeCatalogDocument();
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(MainGuiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cd.writeCatalog();
    }//GEN-LAST:event_makeTgtCatFileBtnActionPerformed

    private void makeMapFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeMapFileBtnActionPerformed
        String srcFwName = String.valueOf(srcFrameworkSelect.getSelectedItem());
        srcFwName = FwNameResolver.resolve(srcFwName);
        String tgtFwName = tgtFwsList.getSelectedValue();
        tgtFwName = FwNameResolver.resolve(tgtFwName);

        if(tgtFwName == null){
            JDialog d = new JDialog(this);
            d.setVisible(false);
            JOptionPane.showMessageDialog(
                    null,
                    "You must have a target framework selected.",
                    "User Action Required",
                    JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        MappingDoc md = new MappingDoc(srcFwName, tgtFwName);
        md.populate();
        try {
            md.writeMappingsFile();
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(MainGuiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_makeMapFileBtnActionPerformed

    private void updateCprtCacheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCprtCacheBtnActionPerformed
        String srcFwName = String.valueOf(srcFrameworkSelect.getSelectedItem());
        srcFwName = FwNameResolver.resolve(srcFwName);
        String tgtFwName = tgtFwsList.getSelectedValue();
        tgtFwName = FwNameResolver.resolve(tgtFwName);

        if(tgtFwName == null){
            JDialog d = new JDialog(this);
            d.setVisible(false);
            JOptionPane.showMessageDialog(
                    null,
                    "You must have a target framework selected.",
                    "User Action Required",
                    JOptionPane.PLAIN_MESSAGE);
            return;
        }
        
        MappingDoc md = new MappingDoc(srcFwName, tgtFwName);
        md.bUpdateCache = true;
        md.populate();
    }//GEN-LAST:event_updateCprtCacheBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainGuiFrame fr = null;
                
                try {
                    // Set System L&F
                    UIManager.setLookAndFeel(
                        UIManager.getSystemLookAndFeelClassName());
                } 
                catch (UnsupportedLookAndFeelException e) {
                   // handle exception
                }
                catch (ClassNotFoundException e) {
                    // handle exception
                }
                catch (InstantiationException e) {
                    // handle exception
                }
                catch (IllegalAccessException e) {
                    // handle exception
                }
                
                try {
                    fr = new MainGuiFrame();
                } catch (URISyntaxException | IOException ex) {
                    Logger.getLogger(MainGuiFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(fr != null){
                    AppUtils.gMainFrame = fr;
                    fr.setVisible(true);
                    ImageIcon img = new ImageIcon("src\\main\\resources\\cyber-esi-logo.png");
                    fr.setIconImage(img.getImage());
                }
            }
        });
    }

    javax.swing.JLabel getOutFolderLbl(){
        return outFolderLbl;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clrSelBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeMapFileBtn;
    private javax.swing.JButton makeSrcCatFileBtn;
    private javax.swing.JButton makeTgtCatFileBtn;
    private javax.swing.JLabel outFolderLbl;
    private javax.swing.JButton prefsBtn;
    private javax.swing.JButton refreshListBtn;
    private javax.swing.JComboBox<String> srcFrameworkSelect;
    private javax.swing.JList<String> tgtFwsList;
    private javax.swing.JButton updateCprtCacheBtn;
    // End of variables declaration//GEN-END:variables
}
